qchain:
    # Путь к папки с данными
    data-path: qchain_data

    # Максимальный размер пула транзакций
    max-pool-size: 1000

    # Узлы для обмена информацией
    peers:
        - 'http://194.61.3.50:8032'

    # Если true, то будет создан genesis block (начальный блок)
    create-genesis-block: true

    # Хост на котором запущена БД
    host: http://localhost:8080

springdoc:
    paths-to-match: /qchain/api/**
logging:
    level:
        io.github.malikzh.qchain: DEBUG
server:
  error:
      include-message: always