qchain:
    data-path: qchain_data
    max-pool-size: 1000
springdoc:
    paths-to-match: /qchain/api/**
logging:
    level:
        io.github.malikzh.qchain: DEBUG
server:
  error:
      include-message: always